[package]
name = "roborace2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ev3dev-lang-rust = { version = "0.13.0", features = ["ev3", "screen"] }
anyhow = "1.0.75"
image = "0.24.6"