# This file belongs on the robot

# To log to the console or to not log to the console
log = true

# when to warn for low reflection
low_ref_warn = 17.0

rotate_arm = false
rotate_arm_speed = 25.0

# the wheel width of the robot, actually something about 14.0
# set to 0 to use no drall!
robot_wheel_width = 16.0
#robot_wheel_width = 0

# the diameter of the base circle
# negative means counter clockwise rotation
diameter = -78.0
#diameter = -100.0
#diameter = -129.0

# table of values that work:
#
# wwidth | diameter | lcenter | speed | l k_p | l k_i | l k_d | real speed | comment
#
# real radius: 78
#   16.0 |    -78.0 |    50.0 |  20.0 |  -2.0 |   0.0 |   0.0 |   6.1 cm/s |
#   16.0 |    -78.0 |    50.0 |  30.0 |  -2.0 |   0.0 |   0.0 |  11.8 cm/s |
#   16.0 |    -78.0 |    50.0 |  40.0 |  -2.0 |   0.0 |   0.0 |  17.1 cm/s |
#   16.0 |    -78.0 |    50.0 |  50.0 |  -2.0 |   0.0 |   0.0 |  22.5 cm/s |
#   16.0 |    -78.0 |    50.0 |  60.0 |  -2.0 |   0.0 |   0.0 |  27.4 cm/s |
#   16.0 |    -78.0 |    50.0 |  70.0 |  -2.0 |   0.0 |   0.0 |  33.2 cm/s |
#   16.0 |    -78.0 |    50.0 |  80.0 |  -2.0 |   0.0 |   0.0 |    .  cm/s | breaks!
#
# real radius: 93 and 98 (the one I drew)
#   16.0 |    -95.0 |    50.0 |  30.0 |  -2.0 |   0.0 |   0.0 |  10.9 cm/s |
#   16.0 |    -95.0 |    50.0 |  40.0 |  -2.0 |   0.0 |   0.0 |  16.0 cm/s |
#   16.0 |    -95.0 |    50.0 |  50.0 |  -2.0 |   0.0 |   0.0 |  20.9 cm/s |
#   16.0 |    -95.0 |    50.0 |  60.0 |  -2.0 |   0.0 |   0.0 |  25.7 cm/s |
#   16.0 |    -95.0 |    50.0 |  70.0 |  -2.0 |   0.0 |   0.0 |  30.7 cm/s | not as optimal, leaves track
#   16.0 |    -95.0 |    50.0 |  80.0 |  -2.0 |   0.0 |   0.0 |    .  cm/s | doesn't work
#
# older values:
#   16.0 |   -100.0 |    50.0 |  50.0 |  -8.0 |   0.0 |  10.0 |
#   16.0 |   -100.0 |    50.0 |  50.0 |  -7.0 |   0.0 |  10.0 |
#
# real radius: 128 and 130
#   16.0 |   -129.0 |    50.0 |  20.0 |  -2.0 |   0.0 |   0.0 |   6.4 cm/s |
#   16.0 |   -129.0 |    50.0 |  30.0 |  -2.0 |   0.0 |   0.0 |  12.0 cm/s |
#   16.0 |   -129.0 |    50.0 |  40.0 |  -2.0 |   0.0 |   0.0 |  17.2 cm/s |
#   16.0 |   -129.0 |    50.0 |  50.0 |  -2.0 |   0.0 |   0.0 |  22.2 cm/s |
#   16.0 |   -129.0 |    50.0 |  60.0 |  -2.0 |   0.0 |   0.0 |  28.5 cm/s |
#   16.0 |   -129.0 |    50.0 |  70.0 |  -2.0 |   0.0 |   0.0 |  33.3 cm/s |
#   16.0 |   -129.0 |    50.0 |  80.0 |  -2.0 |   0.0 |   0.0 |  38.3 cm/s | not as optimal as 70
#
# older values:
#   16.0 |   -129.0 |    50.0 |  50.0 |  -7.0 |   0.0 |  10.0 |
#   16.0 |   -129.0 |    50.0 |  30.0 |  -7.0 |   0.0 |  10.0 |  13.1 cm/s | not optimal
#
# values from the 2023-11-23, circle is -129; no drall!
#   16.0 |   -129.0 |    50.0 |  40.0 |  -6.0 | -0.07 |   0.0 |  17.2 cm/s | ok ish
#   16.0 |   -129.0 |    50.0 |  50.0 |  -6.0 | -0.07 |   0.0 |  22.0 cm/s | wobbles around the line
#   16.0 |   -129.0 |    50.0 |  50.0 |  -6.0 |  0.00 |   0.0 |  22.2 cm/s | doesn't wobble around
#   16.0 |   -129.0 |    50.0 |  60.0 |  -6.0 |  0.00 |   0.0 |  27.5 cm/s | slowly moves to the lines, and fast away
#   16.0 |   -129.0 |    50.0 |  60.0 |  -6.0 |  0.00 |  20.0 |  27.5 cm/s |
#   16.0 |   -129.0 |    50.0 |  70.0 |  -6.0 |  0.00 |  20.0 |  32.4 cm/s | wobbles, but not very much
#   16.0 |   -129.0 |    50.0 |  70.0 |  -4.0 |  0.00 |  30.0 |  30.6 cm/s |
#   16.0 |   -129.0 |    50.0 |  80.0 |  -3.0 |  0.00 |  30.0 |  34.9 cm/s |
#   16.0 |   -129.0 |    50.0 |  90.0 |  -3.0 |  0.00 |  30.0 |  38.4 cm/s |
#   16.0 |   -129.0 |    50.0 | 100.0 |  -4.0 |  0.00 |  30.0 |  38.5 cm/s |
#
# values from same date; circle is -100; no drall!
#   16.0 |   -100.0 |    50.0 |  30.0 |  -6.0 |  0.00 |  30.0 |  10.5 cm/s | on the bad circle leaves track a bit
#   16.0 |   -100.0 |    60.0 |  40.0 |  -6.0 |  0.00 |  30.0 |  15.8 cm/s | driver very safe, tho leaving the track
#
# values for same date; circle is -78; no drall!
#   16.0 |    -78.0 |    60.0 |  40.0 |  -6.0 | -0.07 |  30.0 |  15.8 cm/s | driver very safe, tho leaving the track
#
# wwidth | diameter | lcenter | speed | l k_p | l k_i | l k_d | real speed | comment

# The robot speed.
speed = 80.0

# the distance where if below to try to regulate the distance
distance_trigger = 40.0

# the distance to stop when on the exit track
stop_distance = 20.0

# the PID for regulating the driving
[line]
center = 50.0
k_p = -4.0
k_i = -0.07
k_d = 30.0

# the PID for regulating the distance
[distance]
center = 30.0
k_p = 10.0
k_i = 0.0
k_d = 0.0
